//! Helper `write_tier_artifacts_to`.
#[allow(unused_imports)]
use crate::*;

pub(crate) fn write_tier_artifacts_to(score_rows: &[ScoreAllRow], output_dir: &Path) -> Result<()> {
    let mut rows: Vec<&ScoreAllRow> = score_rows.iter().collect();
    rows.sort_by(|a, b| {
        a.tier
            .cmp(b.tier)
            .then_with(|| b.score.total_cmp(&a.score))
            .then_with(|| a.route.cmp(&b.route))
    });

    std::fs::create_dir_all(output_dir)?;
    let csv_path = output_dir.join("tier-table.csv");
    let mut wtr = csv::Writer::from_path(&csv_path)?;
    wtr.write_record([
        "tier",
        "route",
        "score",
        "rubric_version",
        "estimated",
        "confidence",
        "score_confidence",
        "confidence_label",
        "score_confidence_label",
    ])?;
    for row in &rows {
        wtr.write_record([
            row.tier.to_string(),
            row.route.clone(),
            format!("{:.1}", row.score),
            row.rubric_version.clone(),
            row.estimated.to_string(),
            format!("{:.2}", row.confidence),
            format!("{:.2}", row.score_confidence),
            route_score::confidence_label(row.confidence).to_string(),
            route_score::confidence_label(row.score_confidence).to_string(),
        ])?;
    }
    wtr.flush()?;

    let md_path = output_dir.join("tier-table.md");
    let mut md = String::new();
    md.push_str("# ROUTE Atlas Tier Table\n\n");
    md.push_str("Generated by `route score-all` from `data/scores-all.csv` inputs and the current scoring config.\n\n");
    md.push_str("| Tier | Corridors |\n|---|---:|\n");
    for tier in ["T1", "T2", "T3", "T4"] {
        let count = rows.iter().filter(|row| row.tier == tier).count();
        md.push_str(&format!("| {tier} | {count} |\n"));
    }
    md.push_str("\n| Tier | Route | Score | Score Confidence | Label | Estimated |\n|---|---|---:|---:|---|---|\n");
    for row in &rows {
        md.push_str(&format!(
            "| {} | {} | {:.1} | {:.2} | {} | {} |\n",
            row.tier,
            row.route,
            row.score,
            row.score_confidence,
            route_score::confidence_label(row.score_confidence),
            row.estimated
        ));
    }
    std::fs::write(&md_path, md)?;

    println!("  wrote tier table → {}", csv_path.display());
    println!("  wrote tier table markdown → {}", md_path.display());
    Ok(())
}

