//! Helper `write_missing_link_gap_section`.
#[allow(unused_imports)]
use crate::*;

pub(crate) fn write_missing_link_gap_section(md: &mut String) -> Result<()> {
    md.push_str(
        "Source: `data/coverage-gaps.csv`, regenerated by `route coverage --threshold 30`.\n\n",
    );
    let mut rdr = csv::Reader::from_path("data/coverage-gaps.csv")
        .context("reading data/coverage-gaps.csv")?;
    let mut counts = std::collections::BTreeMap::<String, usize>::new();
    let mut rows = Vec::new();
    for record in rdr.records() {
        let record = record?;
        let class = csv_get(&record, 8).to_string();
        *counts.entry(class.clone()).or_default() += 1;
        if class == "candidate_access_gap" && rows.len() < 20 {
            rows.push(record);
        }
    }

    md.push_str("| Gap class | Counties |\n|---|---:|\n");
    for (class, count) in counts {
        md.push_str(&format!("| {class} | {count} |\n"));
    }
    md.push_str("\n## Top Candidate Access Gaps\n\n");
    md.push_str(
        "| County | State | Nearest mi | Population | Land sq mi |\n|---|---|---:|---:|---:|\n",
    );
    for row in rows {
        md.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            csv_get(&row, 1),
            csv_get(&row, 2),
            csv_get(&row, 5),
            csv_get(&row, 6),
            csv_get(&row, 7)
        ));
    }
    md.push_str("\nInterpretation: `candidate_access_gap` rows are not automatic construction recommendations; they are counties whose Census internal point is beyond the threshold after separating non-CONUS and large-county centroid-risk rows.\n");
    Ok(())
}

