//! Helper `write_score_dimension_gap_section`.
#[allow(unused_imports)]
use crate::*;

pub(crate) fn write_score_dimension_gap_section(
    md: &mut String,
    title: &str,
    description: &str,
    dimension: &str,
    dimension_label: &str,
    descending: bool,
) -> Result<()> {
    md.push_str("Source: `data/scores-all.csv`, regenerated by `route score-all`.\n\n");
    md.push_str(&format!("## {title}\n\n{description}\n\n"));
    let mut rdr = csv::Reader::from_path("data/scores-all.csv").context("reading scores-all")?;
    let headers = rdr.headers()?.clone();
    let dim_idx = headers
        .iter()
        .position(|h| h == dimension)
        .ok_or_else(|| anyhow::anyhow!("dimension column {dimension} not found"))?;
    let conf_idx = headers
        .iter()
        .position(|h| h == format!("{dimension}_conf"))
        .ok_or_else(|| anyhow::anyhow!("dimension confidence column not found"))?;
    let mut rows = Vec::new();
    for record in rdr.records() {
        let row = record?;
        let value = csv_get(&row, dim_idx).parse::<f64>().unwrap_or(0.0);
        rows.push((value, row));
    }
    if descending {
        rows.sort_by(|a, b| b.0.total_cmp(&a.0));
    } else {
        rows.sort_by(|a, b| a.0.total_cmp(&b.0));
    }
    md.push_str(&format!("| Route | Score | Tier | {dimension_label} | Confidence | Claim label |\n|---|---:|---|---:|---:|---|\n"));
    for (_, row) in rows.into_iter().take(20) {
        let confidence = csv_get(&row, conf_idx).parse::<f32>().unwrap_or(0.0);
        md.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            csv_get(&row, 0),
            csv_get(&row, 1),
            csv_get(&row, 2),
            csv_get(&row, dim_idx),
            csv_get(&row, conf_idx),
            route_score::confidence_label(confidence)
        ));
    }
    md.push_str("\nInterpretation: confidence labels describe source/model support for this dimension, not the importance of the corridor. Low or Medium claims need source review before being promoted to project recommendations.\n");
    Ok(())
}
