//! Helper `write_gap_report`.
#[allow(unused_imports)]
use crate::*;

pub(crate) fn write_gap_report(gap_type: &GapType, output_path: &Path) -> Result<()> {
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut md = String::new();
    md.push_str(&format!("# Fault Lines — {}\n\n", gap_type_slug(gap_type)));
    md.push_str(&format!(
        "Generated by `route gap --type {}` on {}.\n\n",
        gap_type_slug(gap_type),
        route_date()
    ));

    match gap_type {
        GapType::MissingLink => write_missing_link_gap_section(&mut md)?,
        GapType::Bottleneck => write_bottleneck_gap_section(&mut md)?,
        GapType::Resilience => write_score_dimension_gap_section(
            &mut md,
            "Resilience Holes",
            "Routes with high D1 climate-resilience exposure under the current score ledger.",
            "D1",
            "D1 climate-resilience exposure",
            true,
        )?,
        GapType::Intermodal => write_intermodal_gap_section(&mut md)?,
    }

    std::fs::write(output_path, md)
        .with_context(|| format!("writing gap report {}", output_path.display()))
}
