//! Extracted from main.rs for maintainability.
use super::*;

pub(crate) fn tier_optimizer_run_rows(all_tiers: bool) -> Result<Vec<TierOptimizerRunRow>> {
    let stages = if all_tiers {
        vec![
            (
                "t1-sla-candidate-pairs",
                "route t1-sla-candidate-pairs --gate",
                "data/t1-sla-candidate-pairs.csv",
                "pass",
                0usize,
                "",
            ),
            (
                "t1-stop-selector",
                "route t1-stop-selector --gate",
                "data/t1-stop-selector.csv",
                "pass",
                0,
                "",
            ),
            (
                "t1-topology-repairs",
                "route t1-topology-repairs --gate",
                "data/t1-topology-repairs.csv",
                "pass",
                0,
                "",
            ),
            (
                "t1-beck-alignment",
                "route t1-beck-alignment --gate",
                "data/t1-beck-alignment.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-region-workloads",
                "route tier-regions --tier T2 --gate",
                "data/tier-region-workloads.csv",
                "held-known",
                2,
                "raw graph rows resolved downstream by Beck contact and relief evidence",
            ),
            (
                "t2-contact-witnesses",
                "route tier-contact-witnesses --gate",
                "data/tier-contact-witnesses.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-contact-resolutions",
                "route t2-contact-resolutions --gate",
                "data/t2-contact-resolutions.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-held-contact-actions",
                "route t2-held-contact-actions --gate",
                "data/t2-held-contact-actions.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-graph-contact-repairs",
                "route t2-graph-contact-repairs --gate",
                "data/t2-graph-contact-repairs.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-parent-contact-validation",
                "route t2-parent-contact-validation --gate",
                "data/t2-parent-contact-validation.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-relief-evidence-docket",
                "route t2-relief-evidence-docket --gate",
                "data/t2-relief-evidence-docket.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-terminal-contact-validation",
                "route t2-terminal-contact-validation --gate",
                "data/t2-terminal-contact-validation.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-blocker-closure",
                "route t2-blocker-closure --gate",
                "data/t2-blocker-closure.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-route-family-splits",
                "route t2-route-family-splits --gate",
                "data/t2-route-family-splits.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-graph-contact-validation",
                "route t2-graph-contact-validation --gate",
                "data/t2-graph-contact-validation.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-contact-closure",
                "route t2-contact-closure --gate",
                "data/t2-contact-closure.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-endpoint-closure",
                "route t2-endpoint-closure --gate",
                "data/t2-endpoint-closure.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-candidate-columns",
                "route tier-candidate-columns --gate",
                "data/tier-candidate-columns.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-bundle-repair-queue",
                "route t2-bundle-repair-queue --gate",
                "data/t2-bundle-repair-queue.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-regionalizer",
                "route t2-regionalizer --gate",
                "data/t2-regionalizer.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-service-selection",
                "route t2-service-selection --gate",
                "data/t2-service-selection.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-service-diagnostic-queue",
                "route t2-service-diagnostic-queue --gate",
                "data/t2-service-diagnostic-queue.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-parallel-service-queue",
                "route t2-parallel-service-queue --gate",
                "data/t2-parallel-service-queue.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-segment-candidates",
                "route tier-segment-candidates --gate",
                "data/tier-segment-candidates.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-docket",
                "route tier-pavement-docket --gate",
                "data/tier-pavement-docket.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-source-gaps",
                "route tier-pavement-source-gaps --gate",
                "data/tier-pavement-source-gaps.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-route-state-exclusions",
                "route tier-pavement-debt-budget --gate",
                "data/tier-pavement-route-state-exclusions.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-repair-funding-acceptance",
                "route tier-pavement-debt-budget --gate",
                "data/tier-pavement-repair-funding-acceptance.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-debt-budget",
                "route tier-pavement-debt-budget --gate",
                "data/tier-pavement-debt-budget.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-acquisition-plan",
                "route tier-pavement-acquisition-plan --gate",
                "data/tier-pavement-acquisition-plan.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-acquisition-docket",
                "route tier-pavement-acquisition-docket --gate",
                "data/tier-pavement-acquisition-docket.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-source-access",
                "route tier-pavement-source-access --gate",
                "data/tier-pavement-source-access.csv",
                "held-known",
                3,
                "priority-A pavement fetches preserve asset-condition blockers until scoped evidence is rebuilt and reviewed",
            ),
            (
                "tier-pavement-source-fetch-attempt",
                "route tier-pavement-source-fetch-attempt --gate",
                "data/tier-pavement-source-fetch-attempt.csv",
                "held-known",
                3,
                "priority-A pavement fetch attempts preserve blockers until cache rows are rebuilt and reviewed",
            ),
            (
                "tier-pavement-source-fetch-review",
                "route tier-pavement-source-fetch-review --gate",
                "data/tier-pavement-source-fetch-review.csv",
                "held-known",
                3,
                "priority-A pavement fetch review preserves blockers while TX/LA/NM joins remain unresolved",
            ),
            (
                "tier-pavement-unmatched-join-review",
                "route tier-pavement-unmatched-join-review --gate",
                "data/tier-pavement-unmatched-join-review.csv",
                "held-known",
                3,
                "priority-A pavement unmatched-join review preserves blockers while source-needed US-route members lack HPMS route evidence",
            ),
            (
                "tier-pavement-hpms-scope-broadening",
                "route tier-pavement-hpms-scope-broadening --gate",
                "data/tier-pavement-hpms-scope-broadening.csv",
                "pass",
                0,
                "",
            ),
            (
                "tier-pavement-repair-debt-review",
                "route tier-pavement-repair-debt-review --gate",
                "data/tier-pavement-repair-debt-review.csv",
                "held-known",
                3,
                "priority-A pavement repair debt is confirmed but claims stay blocked until repair funding, downgrade, exclusion, or accepted relief replay",
            ),
            (
                "tier-pavement-repair-disposition",
                "route tier-pavement-repair-disposition --gate",
                "data/tier-pavement-repair-disposition.csv",
                "held-known",
                3,
                "priority-A pavement repair disposition keeps repair rows relief-ineligible until funding, downgrade, or exclusion",
            ),
            (
                "tier-pavement-repair-funding-package",
                "route tier-pavement-repair-funding-package --gate",
                "data/tier-pavement-repair-funding-package.csv",
                "held-known",
                3,
                "priority-A pavement repair funding package remains unfunded and relief-ineligible until an accepted commitment lands",
            ),
            (
                "tier-pavement-funding-commitment-review",
                "route tier-pavement-funding-commitment-review --gate",
                "data/tier-pavement-funding-commitment-review.csv",
                "held-known",
                3,
                "priority-A pavement funding commitment review finds no accepted commitment attached and preserves blockers",
            ),
            (
                "tier-pavement-downgrade-exclusion-decision",
                "route tier-pavement-downgrade-exclusion-decision --gate",
                "data/tier-pavement-downgrade-exclusion-decision.csv",
                "held-known",
                3,
                "priority-A pavement downgrade/exclusion decision keeps service held at current tier without relief",
            ),
            (
                "tier-pavement-funding-evidence-contract",
                "route tier-pavement-funding-evidence-contract --gate",
                "data/tier-pavement-funding-evidence-contract.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence contract requires accepted full-cost commitment before relief",
            ),
            (
                "tier-pavement-funding-evidence-source-capture",
                "route tier-pavement-funding-evidence-source-capture --gate",
                "data/tier-pavement-funding-evidence-source-capture.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence source capture records no attached artifact and preserves blockers",
            ),
            (
                "tier-pavement-funding-evidence-artifact-attachment",
                "route tier-pavement-funding-evidence-artifact-attachment --gate",
                "data/tier-pavement-funding-evidence-artifact-attachment.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence artifact attachment preserves no accepted artifact and blockers",
            ),
            (
                "tier-pavement-funding-evidence-review-docket",
                "route tier-pavement-funding-evidence-review-docket --gate",
                "data/tier-pavement-funding-evidence-review-docket.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence review preserves unattached artifact holds and blockers",
            ),
            (
                "tier-pavement-funding-evidence-acquisition",
                "route tier-pavement-funding-evidence-acquisition --gate",
                "data/tier-pavement-funding-evidence-acquisition.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence acquisition targets accepted artifacts without relief",
            ),
            (
                "tier-pavement-funding-evidence-source-access",
                "route tier-pavement-funding-evidence-source-access --gate",
                "data/tier-pavement-funding-evidence-source-access.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence source access requires manual or cached accepted artifacts",
            ),
            (
                "tier-pavement-funding-evidence-intake",
                "route tier-pavement-funding-evidence-intake --gate",
                "data/tier-pavement-funding-evidence-intake.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence intake defines metadata requirements without evidence acceptance",
            ),
            (
                "tier-pavement-funding-evidence-metadata-capture",
                "route tier-pavement-funding-evidence-metadata-capture --gate",
                "data/tier-pavement-funding-evidence-metadata-capture.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence metadata capture preserves source-needed artifact holds",
            ),
            (
                "tier-pavement-funding-evidence-accepted-artifact-attachment",
                "route tier-pavement-funding-evidence-accepted-artifact-attachment --gate",
                "data/tier-pavement-funding-evidence-accepted-artifact-attachment.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted artifact attachment preserves source-needed artifact holds",
            ),
            (
                "tier-pavement-funding-evidence-accepted-attachment-review",
                "route tier-pavement-funding-evidence-accepted-attachment-review --gate",
                "data/tier-pavement-funding-evidence-accepted-attachment-review.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted attachment review preserves held no-artifact decisions",
            ),
            (
                "tier-pavement-funding-evidence-accepted-artifact-acquisition",
                "route tier-pavement-funding-evidence-accepted-artifact-acquisition --gate",
                "data/tier-pavement-funding-evidence-accepted-artifact-acquisition.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted artifact acquisition preserves source-needed cache targets",
            ),
            (
                "tier-pavement-funding-evidence-accepted-source-access",
                "route tier-pavement-funding-evidence-accepted-source-access --gate",
                "data/tier-pavement-funding-evidence-accepted-source-access.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted source access requires manual or cached accepted artifacts",
            ),
            (
                "tier-pavement-funding-evidence-accepted-intake",
                "route tier-pavement-funding-evidence-accepted-intake --gate",
                "data/tier-pavement-funding-evidence-accepted-intake.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted intake defines required artifacts without evidence acceptance",
            ),
            (
                "tier-pavement-funding-evidence-accepted-metadata-capture",
                "route tier-pavement-funding-evidence-accepted-metadata-capture --gate",
                "data/tier-pavement-funding-evidence-accepted-metadata-capture.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted metadata capture preserves source-needed artifact holds",
            ),
            (
                "tier-pavement-funding-evidence-accepted-metadata-artifact-attachment",
                "route tier-pavement-funding-evidence-accepted-metadata-artifact-attachment --gate",
                "data/tier-pavement-funding-evidence-accepted-metadata-artifact-attachment.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted metadata artifact attachment preserves source-needed artifact holds",
            ),
            (
                "tier-pavement-funding-evidence-accepted-metadata-attachment-review",
                "route tier-pavement-funding-evidence-accepted-metadata-attachment-review --gate",
                "data/tier-pavement-funding-evidence-accepted-metadata-attachment-review.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted metadata attachment review preserves held no-artifact decisions",
            ),
            (
                "tier-pavement-funding-evidence-accepted-metadata-artifact-acquisition",
                "route tier-pavement-funding-evidence-accepted-metadata-artifact-acquisition --gate",
                "data/tier-pavement-funding-evidence-accepted-metadata-artifact-acquisition.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted metadata artifact acquisition preserves source-needed cache targets",
            ),
            (
                "tier-pavement-funding-evidence-accepted-metadata-source-access",
                "route tier-pavement-funding-evidence-accepted-metadata-source-access --gate",
                "data/tier-pavement-funding-evidence-accepted-metadata-source-access.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted metadata source access requires manual or cached accepted artifacts",
            ),
            (
                "tier-pavement-funding-evidence-accepted-metadata-intake",
                "route tier-pavement-funding-evidence-accepted-metadata-intake --gate",
                "data/tier-pavement-funding-evidence-accepted-metadata-intake.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted metadata intake defines required artifacts without evidence acceptance",
            ),
            (
                "tier-pavement-funding-evidence-accepted-metadata-source-capture",
                "route tier-pavement-funding-evidence-accepted-metadata-source-capture --gate",
                "data/tier-pavement-funding-evidence-accepted-metadata-source-capture.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted metadata source capture preserves source-needed artifact holds",
            ),
            (
                "tier-pavement-funding-evidence-accepted-metadata-source-capture-artifact-attachment",
                "route tier-pavement-funding-evidence-accepted-metadata-source-capture-artifact-attachment --gate",
                "data/tier-pavement-funding-evidence-accepted-metadata-source-capture-artifact-attachment.csv",
                "held-known",
                3,
                "priority-A pavement funding evidence accepted metadata source-capture artifact attachment preserves source-needed artifact holds",
            ),
            (
                "optimizer-constraint-ledger",
                "route optimizer-constraint-ledger --gate",
                "data/optimizer-constraint-ledger.csv",
                "pass",
                0,
                "",
            ),
            (
                "optimizer-constraint-budget",
                "route optimizer-constraint-budget --gate",
                "data/optimizer-constraint-budget.csv",
                "pass",
                0,
                "",
            ),
            (
                "optimizer-residual-blocker-backlog",
                "route optimizer-residual-blocker-backlog --gate",
                "data/optimizer-residual-blocker-backlog.csv",
                "held-known",
                117,
                "Residual constraint-budget blockers are grouped into next optimizer wave families",
            ),
            (
                "optimizer-claim-review",
                "route optimizer-claim-review --gate",
                "data/optimizer-claim-review.csv",
                "held-known",
                31,
                "P1 optimizer claim blockers remain held for source-specific review",
            ),
            (
                "t2-game-publication-evidence-review",
                "route t2-game-publication-evidence-review --gate",
                "data/t2-game-publication-evidence-review.csv",
                "held-known",
                3,
                "T2 game publication readiness blockers remain held pending evidence policy",
            ),
            (
                "t2-game-publication-evidence-policy",
                "route t2-game-publication-evidence-policy --gate",
                "data/t2-game-publication-evidence-policy.csv",
                "held-known",
                3,
                "T2 game publication evidence policy preserves blockers pending acceptance",
            ),
            (
                "t2-game-publication-evidence-policy-acceptance",
                "route t2-game-publication-evidence-policy-acceptance --gate",
                "data/t2-game-publication-evidence-policy-acceptance.csv",
                "held-known",
                3,
                "T2 game publication evidence policy is accepted but pending blocker relief replay",
            ),
            (
                "t2-game-publication-evidence-blocker-relief",
                "route t2-game-publication-evidence-blocker-relief --gate",
                "data/t2-game-publication-evidence-blocker-relief.csv",
                "pass",
                0,
                "",
            ),
            (
                "t1-schematic-geometry-claim-review",
                "route t1-schematic-geometry-claim-review --gate",
                "data/t1-schematic-geometry-claim-review.csv",
                "held-known",
                8,
                "T1 shared schematic geometry blockers remain held pending map policy",
            ),
            (
                "t1-shared-segment-map-policy",
                "route t1-shared-segment-map-policy --gate",
                "data/t1-shared-segment-map-policy.csv",
                "held-known",
                8,
                "T1 shared segment map policy is authored but pending acceptance",
            ),
            (
                "t1-shared-segment-policy-acceptance",
                "route t1-shared-segment-policy-acceptance --gate",
                "data/t1-shared-segment-policy-acceptance.csv",
                "held-known",
                8,
                "T1 shared segment policy is accepted but pending blocker relief replay",
            ),
            (
                "t1-schematic-geometry-blocker-relief",
                "route t1-schematic-geometry-blocker-relief --gate",
                "data/t1-schematic-geometry-blocker-relief.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-beck-transfer-complexity-review",
                "route t2-beck-transfer-complexity-review --gate",
                "data/t2-beck-transfer-complexity-review.csv",
                "held-known",
                6,
                "T2 Beck transfer-complexity blockers remain held pending transfer policy",
            ),
            (
                "t2-beck-label-density-review",
                "route t2-beck-label-density-review --gate",
                "data/t2-beck-label-density-review.csv",
                "held-known",
                5,
                "T2 Beck label-density blockers remain held pending label policy",
            ),
            (
                "t2-beck-long-connector-review",
                "route t2-beck-long-connector-review --gate",
                "data/t2-beck-long-connector-review.csv",
                "held-known",
                3,
                "T2 Beck long-connector blockers remain held pending connector policy",
            ),
            (
                "t2-beck-long-connector-policy",
                "route t2-beck-long-connector-policy --gate",
                "data/t2-beck-long-connector-policy.csv",
                "held-known",
                3,
                "T2 Beck long-connector policy rows preserve blockers pending acceptance",
            ),
            (
                "t2-beck-long-connector-policy-acceptance",
                "route t2-beck-long-connector-policy-acceptance --gate",
                "data/t2-beck-long-connector-policy-acceptance.csv",
                "held-known",
                3,
                "T2 Beck long-connector policy is accepted but pending blocker relief replay",
            ),
            (
                "t2-beck-long-connector-blocker-relief",
                "route t2-beck-long-connector-blocker-relief --gate",
                "data/t2-beck-long-connector-blocker-relief.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-beck-label-density-policy",
                "route t2-beck-label-density-policy --gate",
                "data/t2-beck-label-density-policy.csv",
                "held-known",
                5,
                "T2 Beck label-density policy rows preserve blockers pending acceptance",
            ),
            (
                "t2-beck-label-density-policy-acceptance",
                "route t2-beck-label-density-policy-acceptance --gate",
                "data/t2-beck-label-density-policy-acceptance.csv",
                "held-known",
                5,
                "T2 Beck label-density policy is accepted but pending blocker relief replay",
            ),
            (
                "t2-beck-label-density-blocker-relief",
                "route t2-beck-label-density-blocker-relief --gate",
                "data/t2-beck-label-density-blocker-relief.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-beck-transfer-complexity-policy",
                "route t2-beck-transfer-complexity-policy --gate",
                "data/t2-beck-transfer-complexity-policy.csv",
                "held-known",
                6,
                "T2 Beck transfer-complexity policy is authored but pending acceptance",
            ),
            (
                "t2-beck-transfer-complexity-policy-acceptance",
                "route t2-beck-transfer-complexity-policy-acceptance --gate",
                "data/t2-beck-transfer-complexity-policy-acceptance.csv",
                "held-known",
                6,
                "T2 Beck transfer-complexity policy is accepted but pending blocker relief replay",
            ),
            (
                "t2-beck-transfer-complexity-blocker-relief",
                "route t2-beck-transfer-complexity-blocker-relief --gate",
                "data/t2-beck-transfer-complexity-blocker-relief.csv",
                "pass",
                0,
                "",
            ),
            (
                "t3-lower-tier-feeder-gap-review",
                "route t3-lower-tier-feeder-gap-review --gate",
                "data/t3-lower-tier-feeder-gap-review.csv",
                "held-known",
                6,
                "T3 lower-tier feeder-gap blockers remain held pending feeder policy",
            ),
            (
                "t3-lower-tier-feeder-gap-policy",
                "route t3-lower-tier-feeder-gap-policy --gate",
                "data/t3-lower-tier-feeder-gap-policy.csv",
                "held-known",
                6,
                "T3 lower-tier feeder-gap policy rows preserve blockers pending acceptance",
            ),
            (
                "t3-lower-tier-feeder-gap-policy-acceptance",
                "route t3-lower-tier-feeder-gap-policy-acceptance --gate",
                "data/t3-lower-tier-feeder-gap-policy-acceptance.csv",
                "held-known",
                6,
                "T3 lower-tier feeder-gap policy acceptance preserves blockers pending relief",
            ),
            (
                "t3-lower-tier-feeder-gap-blocker-relief",
                "route t3-lower-tier-feeder-gap-blocker-relief --gate",
                "data/t3-lower-tier-feeder-gap-blocker-relief.csv",
                "pass",
                0,
                "",
            ),
            (
                "source-fetch-policy",
                "route source-fetch-policy --gate",
                "data/source-fetch-policy.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-bundle-overlays",
                "route t2-bundle-overlays --gate",
                "data/game/t2-bundle-overlays.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-game-ops-binding-intake",
                "route t2-game-ops-binding-intake --gate",
                "data/t2-game-ops-binding-intake.csv",
                "held-known",
                16,
                "T2 game ops bundle binding blockers require explicit decisions before game or incident use",
            ),
            (
                "t2-game-ops-binding-decisions",
                "route t2-game-ops-binding-decisions --gate",
                "data/t2-game-ops-binding-decisions.csv",
                "held-known",
                16,
                "T2 game ops binding decisions preserve residual repair-needed and held blockers",
            ),
            (
                "t2-bundle-overlay-repair-targets",
                "route t2-bundle-overlay-repair-targets --gate",
                "data/t2-bundle-overlay-repair-targets.csv",
                "held-known",
                16,
                "Residual T2 game ops binding decisions are classified into explicit repair targets",
            ),
            (
                "t2-service-class-repair-docket",
                "route t2-service-class-repair-docket --gate",
                "data/t2-service-class-repair-docket.csv",
                "held-known",
                15,
                "Service-class-held T2 overlay rows remain routed to Beck service or local-zone repair work",
            ),
            (
                "t2-game-ops-bundle-evidence-review",
                "route t2-game-ops-bundle-evidence-review --gate",
                "data/t2-game-ops-bundle-evidence-review.csv",
                "held-known",
                16,
                "Residual T2 game ops bundle-binding rows remain bound to downstream evidence without blocker relief",
            ),
            (
                "t2-game-ops-bundle-evidence-policy",
                "route t2-game-ops-bundle-evidence-policy --gate",
                "data/t2-game-ops-bundle-evidence-policy.csv",
                "held-known",
                16,
                "T2 game ops bundle evidence policy preserves residual blockers pending acceptance",
            ),
            (
                "t2-game-ops-bundle-evidence-policy-acceptance",
                "route t2-game-ops-bundle-evidence-policy-acceptance --gate",
                "data/t2-game-ops-bundle-evidence-policy-acceptance.csv",
                "held-known",
                16,
                "T2 game ops bundle evidence policy acceptance preserves blockers pending relief",
            ),
            (
                "t2-game-ops-bundle-evidence-blocker-relief",
                "route t2-game-ops-bundle-evidence-blocker-relief --gate",
                "data/t2-game-ops-bundle-evidence-blocker-relief.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-service-overlay-diagnostic-decisions",
                "route t2-service-overlay-diagnostic-decisions --gate",
                "data/t2-service-overlay-diagnostic-decisions.csv",
                "held-known",
                7,
                "Service-overlay T2 rows remain held behind explicit Beck diagnostic decisions",
            ),
            (
                "t2-local-zone-overlay-handoff",
                "route t2-local-zone-overlay-handoff --gate",
                "data/t2-local-zone-overlay-handoff.csv",
                "held-known",
                8,
                "Local-zone T2 rows remain held below national game overlay through T3 zone handoff",
            ),
            (
                "t2-bundle-readiness-disposition",
                "route t2-bundle-readiness-disposition --gate",
                "data/t2-bundle-readiness-disposition.csv",
                "held-known",
                10,
                "T2 overlay rows needing stop-chain, stitched-member, or terminal-stop repair remain blocked",
            ),
            (
                "t2-bundle-readiness-repair-docket",
                "route t2-bundle-readiness-repair-docket --gate",
                "data/t2-bundle-readiness-repair-docket.csv",
                "held-known",
                4,
                "Repair-needed T2 bundle-readiness rows are explicit structural repair tasks",
            ),
            (
                "t2-bundle-readiness-repair-evidence",
                "route t2-bundle-readiness-repair-evidence --gate",
                "data/t2-bundle-readiness-repair-evidence.csv",
                "held-known",
                4,
                "Readiness repair tasks are probed against downstream evidence before replay",
            ),
            (
                "t2-bundle-readiness-replay-decisions",
                "route t2-bundle-readiness-replay-decisions --gate",
                "data/t2-bundle-readiness-replay-decisions.csv",
                "held-known",
                4,
                "Readiness evidence probes become explicit replay decisions without claim promotion",
            ),
            (
                "t2-national-bundle-readiness-audit",
                "route t2-national-bundle-readiness-audit --gate",
                "data/t2-national-bundle-readiness-audit.csv",
                "held-known",
                4,
                "Readiness replay decisions are audited against national bundle structural status",
            ),
            (
                "t2-stitched-member-registry-handoff",
                "route t2-stitched-member-registry-handoff --gate",
                "data/t2-stitched-member-registry-handoff.csv",
                "held-known",
                2,
                "Stitched-member readiness blockers are bound to registry and candidate evidence",
            ),
            (
                "t2-stitched-member-candidate-scope-review",
                "route t2-stitched-member-candidate-scope-review --gate",
                "data/t2-stitched-member-candidate-scope-review.csv",
                "held-known",
                2,
                "Route-level stitched candidate evidence is scoped before bundle membership repair",
            ),
            (
                "t2-stitched-member-decision-docket",
                "route t2-stitched-member-decision-docket --gate",
                "data/t2-stitched-member-decision-docket.csv",
                "held-known",
                2,
                "Stitched-member scope findings become split merge or expand repair decisions",
            ),
            (
                "t2-stitched-member-split-plan",
                "route t2-stitched-member-split-plan --gate",
                "data/t2-stitched-member-split-plan.csv",
                "held-known",
                2,
                "Stitched-member split decisions become state-scoped candidate bundle review rows",
            ),
            (
                "t2-stitched-member-selection-docket",
                "route t2-stitched-member-selection-docket --gate",
                "data/t2-stitched-member-selection-docket.csv",
                "held-known",
                2,
                "Stitched-member split rows become evidence-needed selection review rows",
            ),
            (
                "t2-stitched-member-evidence-contract",
                "route t2-stitched-member-evidence-contract --gate",
                "data/t2-stitched-member-evidence-contract.csv",
                "held-known",
                2,
                "Stitched-member selection rows receive source-needed evidence contracts",
            ),
            (
                "t2-stitched-member-evidence-acquisition",
                "route t2-stitched-member-evidence-acquisition --gate",
                "data/t2-stitched-member-evidence-acquisition.csv",
                "held-known",
                2,
                "Stitched-member evidence contracts become source-needed acquisition targets",
            ),
            (
                "t2-stitched-member-source-access-policy",
                "route t2-stitched-member-source-access-policy --gate",
                "data/t2-stitched-member-source-access-policy.csv",
                "held-known",
                2,
                "Stitched-member acquisition targets receive manual or cached source-access policy",
            ),
            (
                "t2-stitched-member-proof-intake",
                "route t2-stitched-member-proof-intake --gate",
                "data/t2-stitched-member-proof-intake.csv",
                "held-known",
                2,
                "Stitched-member source-access rows receive proof-intake artifact contracts",
            ),
            (
                "t2-stitched-member-proof-source-capture",
                "route t2-stitched-member-proof-source-capture --gate",
                "data/t2-stitched-member-proof-source-capture.csv",
                "held-known",
                2,
                "Stitched-member proof-intake rows receive source-capture placeholders",
            ),
            (
                "t2-stitched-member-proof-artifact-attachment",
                "route t2-stitched-member-proof-artifact-attachment --gate",
                "data/t2-stitched-member-proof-artifact-attachment.csv",
                "held-known",
                2,
                "Stitched-member source-capture rows receive artifact-attachment placeholders",
            ),
            (
                "t2-stitched-member-proof-review-docket",
                "route t2-stitched-member-proof-review-docket --gate",
                "data/t2-stitched-member-proof-review-docket.csv",
                "held-known",
                2,
                "Stitched-member artifact-attachment rows return to optimizer held-known proof review",
            ),
            (
                "t2-bundle-overlay-repair-delta",
                "route t2-bundle-overlay-repair-delta --gate",
                "data/t2-bundle-overlay-repair-delta.csv",
                "held-known",
                16,
                "T2 overlay repair replay preserves residual held and repair-needed blockers",
            ),
            (
                "t2-overlay-optimizer-action-docket",
                "route t2-overlay-optimizer-action-docket --gate",
                "data/t2-overlay-optimizer-action-docket.csv",
                "held-known",
                16,
                "Residual T2 overlay repair deltas are routed to optimizer action families",
            ),
            (
                "t2-overlay-p1-structural-readiness-review",
                "route t2-overlay-p1-structural-readiness-review --gate",
                "data/t2-overlay-p1-structural-readiness-review.csv",
                "held-known",
                2,
                "P1 structural-readiness overlay actions are reviewed before lower-priority optimizer work",
            ),
            (
                "t2-overlay-p2-service-overlay-review",
                "route t2-overlay-p2-service-overlay-review --gate",
                "data/t2-overlay-p2-service-overlay-review.csv",
                "held-known",
                6,
                "P2 service-overlay actions are held for diagnostic review before optimizer promotion",
            ),
            (
                "t2-overlay-p3-local-zone-overlay-review",
                "route t2-overlay-p3-local-zone-overlay-review --gate",
                "data/t2-overlay-p3-local-zone-overlay-review.csv",
                "held-known",
                8,
                "P3 local-zone overlay actions are held below national game overlay promotion",
            ),
            (
                "lower-tier-pressure-witnesses",
                "route lower-tier-pressure-witnesses --gate",
                "data/lower-tier-pressure-witnesses.csv",
                "pass",
                0,
                "",
            ),
            (
                "t3-t4-pressure-intake",
                "route t3-t4-pressure-intake --gate",
                "data/t3-t4-pressure-intake.csv",
                "pass",
                0,
                "",
            ),
            (
                "t3-zone-access-obligations",
                "route t3-zone-access-obligations --gate",
                "data/t3-zone-access-obligations.csv",
                "pass",
                0,
                "",
            ),
            (
                "t3-zone-route-columns",
                "route t3-zone-route-columns --gate",
                "data/t3-zone-route-columns.csv",
                "pass",
                0,
                "",
            ),
            (
                "t4-terminal-access-columns",
                "route t4-terminal-access-columns --gate",
                "data/t4-terminal-access-columns.csv",
                "pass",
                0,
                "",
            ),
            (
                "t4-terminal-contact-evidence",
                "route t4-terminal-contact-evidence --gate",
                "data/t4-terminal-contact-evidence.csv",
                "pass",
                0,
                "",
            ),
            (
                "t4-terminal-access-evidence-review",
                "route t4-terminal-access-evidence-review --gate",
                "data/t4-terminal-access-evidence-review.csv",
                "held-known",
                69,
                "T4 terminal-access evidence blockers remain source-needed until non-seed proof exists",
            ),
            (
                "t4-terminal-access-proof-acquisition",
                "route t4-terminal-access-proof-acquisition --gate",
                "data/t4-terminal-access-proof-acquisition.csv",
                "held-known",
                69,
                "T4 terminal-access proof acquisition tasks require non-seed contact evidence",
            ),
            (
                "t4-terminal-access-proof-artifacts",
                "route t4-terminal-access-proof-artifacts --gate",
                "data/t4-terminal-access-proof-artifacts.csv",
                "held-known",
                69,
                "T4 terminal-access proof artifacts remain unattached until non-seed source capture",
            ),
            (
                "t4-terminal-access-proof-review",
                "route t4-terminal-access-proof-review --gate",
                "data/t4-terminal-access-proof-review.csv",
                "held-known",
                69,
                "T4 terminal-access proof review returns unattached artifacts to optimizer hold",
            ),
            (
                "t4-terminal-access-source-access",
                "route t4-terminal-access-source-access --gate",
                "data/t4-terminal-access-source-access.csv",
                "held-known",
                69,
                "T4 terminal-access source access policy requires manual or cached non-seed proof",
            ),
            (
                "t4-terminal-access-proof-intake",
                "route t4-terminal-access-proof-intake --gate",
                "data/t4-terminal-access-proof-intake.csv",
                "held-known",
                69,
                "T4 terminal-access proof intake requires source-needed manual or cached artifacts",
            ),
            (
                "t4-terminal-access-proof-source-capture",
                "route t4-terminal-access-proof-source-capture --gate",
                "data/t4-terminal-access-proof-source-capture.csv",
                "held-known",
                69,
                "T4 terminal-access proof source capture remains source-needed before attachment",
            ),
            (
                "t4-terminal-access-proof-artifact-attachment",
                "route t4-terminal-access-proof-artifact-attachment --gate",
                "data/t4-terminal-access-proof-artifact-attachment.csv",
                "held-known",
                69,
                "T4 terminal-access proof artifact attachment remains source-needed before review",
            ),
            (
                "t4-terminal-access-proof-attachment-review",
                "route t4-terminal-access-proof-attachment-review --gate",
                "data/t4-terminal-access-proof-attachment-review.csv",
                "held-known",
                69,
                "T4 terminal-access proof attachment review returns unattached source-needed artifacts to optimizer hold",
            ),
            (
                "t4-terminal-access-proof-artifact-acquisition-targets",
                "route t4-terminal-access-proof-artifact-acquisition-targets --gate",
                "data/t4-terminal-access-proof-artifact-acquisition-targets.csv",
                "held-known",
                69,
                "T4 terminal-access proof artifact acquisition targets require non-seed cached proof before blocker relief",
            ),
            (
                "t4-terminal-access-proof-artifact-source-access",
                "route t4-terminal-access-proof-artifact-source-access --gate",
                "data/t4-terminal-access-proof-artifact-source-access.csv",
                "held-known",
                69,
                "T4 terminal-access proof artifact source access requires manual or cached non-seed proof",
            ),
            (
                "t4-terminal-contact-source-plan",
                "route t4-terminal-contact-source-plan --gate",
                "data/t4-terminal-contact-source-plan.csv",
                "held-known",
                69,
                "Terminal contact source plan rows remain source-needed",
            ),
            (
                "t4-terminal-contact-source-catalog",
                "route t4-terminal-contact-source-plan --gate",
                "data/t4-terminal-contact-source-catalog.csv",
                "held-known",
                23,
                "Terminal district source families remain source-needed",
            ),
            (
                "t4-terminal-contact-proof-docket",
                "route t4-terminal-contact-source-plan --gate",
                "data/t4-terminal-contact-proof-docket.csv",
                "held-known",
                69,
                "Route contact proof tasks remain source-needed",
            ),
            (
                "t4-terminal-contact-proof-artifact-contract",
                "route t4-terminal-contact-proof-artifact-contract --gate",
                "data/t4-terminal-contact-proof-artifact-contract.csv",
                "pass",
                0,
                "",
            ),
            (
                "t4-terminal-contact-proof-source-registry",
                "route t4-terminal-contact-proof-source-registry --gate",
                "data/t4-terminal-contact-proof-source-registry.csv",
                "held-known",
                68,
                "Terminal contact proof source registry rows remain source-needed until manual or cached proof artifacts are attached",
            ),
            (
                "t4-terminal-contact-district-proof-import",
                "route t4-terminal-contact-district-proof-import --gate",
                "data/t4-terminal-contact-district-proof-import.csv",
                "held-known",
                8,
                "Largest unresolved terminal district import remains source-needed without manual or cached proof artifacts",
            ),
            (
                "t4-terminal-columbus-proof-intake",
                "route t4-terminal-columbus-proof-intake --gate",
                "data/t4-terminal-columbus-proof-intake.csv",
                "held-known",
                8,
                "Columbus South proof intake rows remain source-needed",
            ),
            (
                "t4-terminal-columbus-source-access",
                "route t4-terminal-columbus-source-access --gate",
                "data/t4-terminal-columbus-source-access.csv",
                "held-known",
                8,
                "Columbus South source access requires manual or cached proof artifacts",
            ),
            (
                "t4-terminal-columbus-proof-attempts",
                "route t4-terminal-columbus-proof-attempts --gate",
                "data/t4-terminal-columbus-proof-attempts.csv",
                "held-known",
                8,
                "Columbus South route proof attempts are blocked without non-seed proof artifacts",
            ),
            (
                "t4-terminal-scenario-readiness",
                "route t4-terminal-scenario-readiness --gate",
                "data/t4-terminal-scenario-readiness.csv",
                "held-known",
                69,
                "terminal contact rows remain source-needed; scenario docket is held empty",
            ),
            (
                "t3-t4-access-gaps",
                "route t3-t4-access-gaps --gate",
                "data/t3-t4-access-gaps.csv",
                "pass",
                0,
                "",
            ),
            (
                "t3-zone-map-diagnostics",
                "route t3-zone-map-diagnostics --gate",
                "data/t3-zone-map-diagnostics.csv",
                "pass",
                0,
                "",
            ),
            (
                "t3-zone-render-board",
                "route t3-zone-render-board --gate",
                "data/t3-zone-render-board.csv",
                "pass",
                0,
                "",
            ),
            (
                "t3-zone-stop-placement",
                "route t3-zone-stop-placement --gate",
                "data/t3-zone-stop-placement.csv",
                "pass",
                0,
                "",
            ),
            (
                "national-segment-registry",
                "route national-segment-registry --gate",
                "data/national-segment-registry.csv",
                "pass",
                0,
                "",
            ),
            (
                "national-segment-bundles",
                "route national-segment-bundles --gate",
                "data/national-segment-bundles.csv",
                "pass",
                0,
                "",
            ),
            (
                "bundle-architecture",
                "route bundle-architecture --gate",
                "data/bundle-architecture.csv",
                "pass",
                0,
                "",
            ),
            (
                "t2-bubble-up-review",
                "route t2-bubble-up-review --gate",
                "data/t2-bubble-up-review.csv",
                "pass",
                0,
                "",
            ),
            (
                "t1-feedback-docket",
                "route t1-feedback-docket --gate",
                "data/t1-feedback-docket.csv",
                "pass",
                0,
                "",
            ),
        ]
    } else {
        vec![(
            "t2-candidate-columns",
            "route tier-candidate-columns --gate",
            "data/tier-candidate-columns.csv",
            "pass",
            0usize,
            "",
        )]
    };

    stages
        .into_iter()
        .enumerate()
        .map(
            |(
                idx,
                (optimizer_stage, command, artifact, gate_status, blocker_count, blocker_summary),
            )| {
                let row_count = csv_record_count(Path::new(artifact))?;
                Ok(TierOptimizerRunRow {
                    step: idx + 1,
                    optimizer_stage: optimizer_stage.to_string(),
                    command: command.to_string(),
                    artifact: artifact.to_string(),
                    row_count,
                    gate_status: gate_status.to_string(),
                    blocker_count,
                    blocker_summary: blocker_summary.to_string(),
                    validation_status: if row_count == 0 {
                        "missing-or-empty".to_string()
                    } else if gate_status == "pass" {
                        "pass".to_string()
                    } else {
                        "held".to_string()
                    },
                })
            },
        )
        .collect()
}

